ARC specific Home page and Component List
sourcefuse/angular-boilerplate pull request #22
Opened 2023-12-26 08:54 UTC by Deepika516

## Description

Design home Page according to ARC theme and add list of Components in Sidebar

Fixes  GH-18

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-05 07:09 UTC, yeshamavani requested changes

2024-01-05 07:09 UTC, yeshamavani commented on projects/arc/src/app/main/introduction/introduction.component.ts
> +    console.log(this.router.url)
remove this

2024-01-05 07:52 UTC, Deepika516 commented on projects/arc/src/app/main/introduction/introduction.component.ts
> +    console.log(this.router.url)
Done

2024-01-05 07:54 UTC, Deepika516 commented on projects/arc/src/app/main/introduction/introduction.component.scss
yes the .parent class is the common class css i kept that class in common the rest is same name but not same content in that

2024-01-08 13:16 UTC, rohit-sourcefuse approved these changes

2024-01-09 05:52 UTC, yeshamavani approved these changes

2024-01-09 05:52 UTC, merged