Frontend Backend Integartion of Admin Portal of SAAS UI
sourcefuse/angular-boilerplate pull request #37
Opened 2024-04-26 08:43 UTC by Deepika516

## Description

frontend backkend Integration

Fixes #GH-26

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-04-29 05:18 UTC, yeshamavani commented
@Surbhi-sharma1 @Deepika516 why is commitlint not configured here 
this is not how we write our commit messages 
raise a separate PR for that first

2024-05-02 13:50 UTC, yeshamavani requested changes

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/main/plan-items/plan-items.component.ts
> +    },
??

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/main/plan-items/plan-items.component.ts
> +  }
??

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/main/plan-items/plan-items.component.ts
> +    this.gridApi.setRowData(this.rowData); // Update the grid data
hard code

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/main/tenant-list/commands/get-tenant-lead.command.ts
> +  }
why this comment 
is the baseApiUrl needed or not ?

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/on-boarding/adapters/validate-lead-adapter.service.ts
> +  }
If there is nothing specific and we are using any types only 
then why not use AnyAdapter

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/on-boarding/add-lead/add-lead.component.html
> +          <h3>Welcome to SAAS UI by SourceFuse</h3>
do the changes we discussed on call

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/on-boarding/add-lead/add-lead.component.ts
> +      console.log(userData);
remove console

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/on-boarding/add-lead/add-lead.module.ts
> +})
why make modules for each component 
when they can be managed under same root module of on-boarding

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/on-boarding/add-tenant/add-tenant.component.ts
> +  ];
it should be fetch via api call

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/on-boarding/commands/delete-lead-command.ts
where is this being used ?

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/on-boarding/commands/get-lead-command.ts
> +  }
somewhere baseurl is included and some places its not
why this ambiguity

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/on-boarding/commands/get-lead-by-id.command.ts
> +    );
someplaces its tenant mgmt service while some place is facade 
why create confusion for user

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/on-boarding/email-verification/email-verification.component.ts
> +    this.router.navigate(['/tenant/add-tenant']);
why a redirection from here 
add-tenant will be called through the link send via email

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/on-boarding/on-boarding-routing.module.ts
> +        // canActivate: [EmailVerifyGuard],
??

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/on-boarding/on-boarding-service.ts
> +        .set(AuthTokenSkipHeader, '-')
why skip header here

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/shared /api/api.service.ts
has a space in name

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/shared /auth/auth.service.ts
why repeating the auth service in lib and project

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/shared /auth/auth.service.ts
> +  // sonarignore:start
why sonarignore

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/shared /auth/auth.service.ts
> +        client_id: this.appConfig.clientId,
where are these function being used if not needed please remove this

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/shared /auth/auth.service.ts
multiple functions in this file that are most probably not being used anywhere 
remove them keep only required code

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/shared /auth/auth.service.ts
> +  loginViaGoogle(): void {
this is not being used

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/shared /auth/commands/del-api.command.ts
this shoudl have been a part of the library, dont repeat the code 
same for all base commads

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/app/shared /auth/commands/google-login.command.ts
again

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/assets/images/Illustration.svg
where is this image used

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/assets/images/Illustration.svg
also why are we repeating images as well 
should not this also be a part of the library

2024-05-02 13:50 UTC, yeshamavani commented on projects/saas-ui/src/assets/images/auth/logo.png
??

2024-05-07 13:55 UTC, Surbhi-sharma1 commented
Closed as not required

2024-05-07 13:59 UTC, Surbhi-sharma1 commented
Close

2024-05-07 13:59 UTC, closed without merging