feat(arc-saas): update add-plan component with features
sourcefuse/angular-boilerplate pull request #66
Opened 2024-08-10 13:14 UTC by Deepika516

## Description
update add-plan component with features

Fixes #64 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-08-12 12:11 UTC, yeshamavani requested changes

2024-08-12 12:11 UTC, yeshamavani commented on projects/saas-ui/src/app/main/components/manage-plans/manage-plans.component.ts
> +          });
```suggestion
              cycleName: item['billingCycle']?.cycleName,
                
              currencyName: item['currency']?.currencyName,
                
              price: item.price,
            };
          });
```

2024-08-22 13:36 UTC, yeshamavani requested changes

2024-08-22 13:36 UTC, yeshamavani commented on projects/saas-ui/src/app/main/components/add-plan/add-plan.component.html
if not needed remove commented code

2024-08-22 13:36 UTC, yeshamavani commented on projects/saas-ui/src/app/main/components/add-plan/add-plan.component.html
> +                    placeholder="Select Plan"
wrong placeholder

2024-08-22 13:36 UTC, yeshamavani commented on projects/saas-ui/src/app/main/components/add-plan/add-plan.component.spec.ts
commented code

2024-08-22 13:36 UTC, yeshamavani commented on projects/saas-ui/src/app/main/components/add-plan/add-plan.component.ts
> +  featureValue: PlanWithFeatures | any;
why any needed here

2024-08-28 07:39 UTC, Deepika516 commented on projects/arc-lib/src/lib/core/auth/auth.service.ts
> +    clientSecret.value = '3be3tt3bkl6sf1pkdiurejejm7phdvhd1fnkch7esiva38p6g6v';
done

2024-08-28 07:40 UTC, Deepika516 commented on projects/saas-ui/src/app/main/commands/add-features.command.ts
> +  }
i was testing i revomed from everywher but by mistake ye rh gya shyd ...anyways removed

2024-08-28 07:40 UTC, Deepika516 commented on projects/saas-ui/src/app/main/commands/get-feature-by-id.command.ts
> +export class GetFeatureByIdCommand<T> extends GetAPICommand<PlanWithFeatures> {
ok sure

2024-08-28 07:40 UTC, Deepika516 commented on projects/saas-ui/src/app/main/commands/edit-features.command.ts
> +export class EditFeaturesCommand<T> extends PatchAPICommand<T> {
ok done

2024-08-28 07:43 UTC, Deepika516 commented on projects/arc-lib/src/lib/components/gantt/services/gantt.service.spec.ts
> +  let service: GanttService<any>;
its gantt spec any ways i ll do that

2024-08-28 07:47 UTC, Deepika516 commented on projects/saas-ui/src/app/main/components/add-plan/add-plan.component.html
> +                    placeholder="Select Plan"
changed

2024-08-28 07:47 UTC, Deepika516 commented on projects/saas-ui/src/app/main/components/add-plan/add-plan.component.spec.ts
i m working on its test casees

2024-09-19 09:35 UTC, yeshamavani commented on projects/saas-ui/src/app/main/commands/add-features.command.ts
again addFeatures name is confusing 
it should be AddFeaturesForPlans
make changes at required places

2024-09-19 09:35 UTC, yeshamavani commented on projects/saas-ui/src/app/main/components/add-plan/add-plan.component.ts
> +  featureValue: PlanWithFeatures | any;
???

2024-09-19 09:51 UTC, Deepika516 commented on projects/saas-ui/src/app/main/commands/add-features.command.ts
ok sure

2024-09-19 09:52 UTC, Deepika516 commented on projects/saas-ui/src/app/main/components/add-plan/add-plan.component.ts
> +  featureValue: PlanWithFeatures | any;
removed

2024-09-19 11:54 UTC, yeshamavani approved these changes

2024-09-19 11:54 UTC, merged