(Arc-Saas):Update the feature when edit the plan
sourcefuse/angular-boilerplate pull request #92
Opened 2024-10-08 12:23 UTC by Deepika516

## Description
Update the feature when edit the plan

Fixes #91 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-16 11:15 UTC, yeshamavani commented
Is this tested ? @Deepika516

2024-10-17 11:09 UTC, Deepika516 commented
> Is this tested ? @Deepika516

Yes Mam tested

2024-10-21 11:35 UTC, yeshamavani requested changes

2024-10-21 11:35 UTC, yeshamavani commented on projects/saas-ui/src/app/main/components/add-plan/add-plan.component.ts
> +            // )
remove commented code

2024-10-28 05:55 UTC, yeshamavani approved these changes

2024-10-28 05:55 UTC, merged