fix(arc-saas): disable button after submit the tenant
sourcefuse/angular-boilerplate pull request #96
Opened 2024-10-22 05:51 UTC by Deepika516

GH-73

## Description
Disable button after submit the tenant on Tenant Registration component

Fixes #73 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-23 08:31 UTC, Surbhi-sharma1 approved these changes

2024-10-29 06:19 UTC, yeshamavani requested changes

2024-10-29 06:19 UTC, yeshamavani commented on projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.ts
> +          this.isSubmitting = false;
why is this needed @Surbhi-sharma1

2024-11-04 06:45 UTC, Surbhi-sharma1 commented on projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.ts
> +          this.isSubmitting = false;
Removed

2024-11-05 06:28 UTC, merged